name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download cleve repo
      uses: actions/checkout@v4

    - name: Add sqlx cli to environment so later we can cache eve sde db queries for macro use
      run: cargo install sqlx-cli

    - name: Add wget and use it to download the EVE SDE from fuzzworks
      uses: wei/wget@v1
      with:
        args: -O sqlite-latest.sqlite.bz2 https://www.fuzzwork.co.uk/dump/sqlite-latest.sqlite.bz2

    - name: Add 7zip to actions environment and decompress the EVE SDE from fuzzworks
      uses: milliewalky/setup-7-zip@v2
      with:
        # 7-Zip release tag from its GitHub Releases page e.g. 24.07.
        # default: latest
        tag: "latest"

    - name: Run 7zip to decompress EVE SDE
      run: 7z x sqlite-latest.sqlite.bz2

    - name: Prepare db queries for macro use
      run: cargo sqlx prepare

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

